import { Volunteer, Site, Assignment } from '@/types';

export const sampleVolunteers: Record<string, Volunteer> = {
  'vol-1': {
    id: 'vol-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@example.com',
    password: 'demo123',
    phone: '416-555-0101',
    joinDate: new Date('2024-01-15'),
    status: 'active',
    role: 'admin',
    skills: ['Tree Identification', 'Pruning', 'Group Leadership'],
    availability: [],
    totalHours: 45,
    certifications: [],
    notes: 'Experienced volunteer and site coordinator',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  'vol-2': {
    id: 'vol-2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@example.com',
    password: 'demo123',
    phone: '416-555-0102',
    joinDate: new Date('2024-02-01'),
    status: 'active',
    role: 'coordinator',
    skills: ['Planting', 'Watering', 'First Aid'],
    availability: [],
    totalHours: 32,
    certifications: [],
    notes: 'Coordinator for High Park',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  'vol-3': {
    id: 'vol-3',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.rodriguez@example.com',
    password: 'demo123',
    phone: '416-555-0103',
    joinDate: new Date('2024-03-10'),
    status: 'active',
    role: 'volunteer',
    skills: ['Watering', 'Mulching'],
    availability: [],
    totalHours: 18,
    certifications: [],
    notes: 'New volunteer, very enthusiastic',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  'vol-4': {
    id: 'vol-4',
    firstName: 'David',
    lastName: 'Thompson',
    email: 'david.thompson@example.com',
    password: 'demo123',
    phone: '416-555-0104',
    joinDate: new Date('2024-01-20'),
    status: 'active',
    role: 'volunteer',
    skills: ['Tree Identification', 'Photography', 'Data Collection'],
    availability: [],
    totalHours: 28,
    certifications: [],
    notes: 'Great at documenting our work',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
};

export const sampleSites: Record<string, Site> = {
  'site-1': {
    id: 'site-1',
    name: 'Aviation Parkway',
    description: 'Large urban park with diverse tree species and natural areas. Home to over 300 trees including rare oak species.',
    address: 'Aviation Parkway',
    city: 'Ottawa',
    province: 'Ontario',
    postalCode: 'K1K 3W3',
    siteType: 'standard-planting',
    size: 161,
    treeCount: 312,
    species: [],
    accessibility: {
      wheelchairAccessible: true,
      parkingAvailable: true,
      publicTransitNearby: true,
      restrooms: true,
    },
    amenities: ['Parking', 'Restrooms', 'Water Access'],
    coordinatorId: 'vol-2',
    status: 'active',
    photos: [],
    notes: 'Popular site with regular maintenance needs',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  'site-2': {
    id: 'site-2',
    name: 'Hogsback Park',
    description: 'Community park with mature trees and open green spaces. Focus on native species restoration.',
    address: '790 Queen Street West',
    city: 'Ottawa',
    province: 'Ontario',
    postalCode: 'K1K 3W3',
    siteType: 'standard-planting',
    size: 38,
    treeCount: 156,
    species: [],
    accessibility: {
      wheelchairAccessible: true,
      parkingAvailable: false,
      publicTransitNearby: true,
      restrooms: true,
    },
    amenities: ['Restrooms', 'Water Access'],
    status: 'active',
    photos: [],
    notes: 'High foot traffic area',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  'site-3': {
    id: 'site-3',
    name: 'Riverdale Tiny Forest',
    description: 'Tiny forest with fruit trees and edible plants. Ottawa Community Housing site.',
    address: '250 Riverdale Drive',
    city: 'Ottawa',
    province: 'Ontario',
    postalCode: 'K1K 3W3',
    siteType: 'tiny-forest',
    size: 2,
    treeCount: 24,
    species: [],
    accessibility: {
      wheelchairAccessible: true,
      parkingAvailable: true,
      publicTransitNearby: true,
      restrooms: false,
    },
    amenities: ['Parking', 'Tool Storage'],
    coordinatorId: 'vol-1',
    status: 'active',
    photos: [],
    notes: 'Seasonal activities, most active spring through fall',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  'site-4': {
    id: 'site-4',
    name: 'Queen Elizabeth Public School',
    description: 'Private property tree planting initiative.',
    address: 'Bloor Street West',
    city: 'Ottawa',
    province: 'Ontario',
    postalCode: 'K1K 3W3',
    siteType: 'private-property',
    size: 5,
    treeCount: 89,
    species: [],
    accessibility: {
      wheelchairAccessible: true,
      parkingAvailable: false,
      publicTransitNearby: true,
      restrooms: false,
    },
    amenities: [],
    status: 'active',
    photos: [],
    notes: 'Street-side maintenance requires traffic awareness',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
};

export const sampleAssignments: Record<string, Assignment> = {
  'assign-1': {
    id: 'assign-1',
    siteId: 'site-1',
    date: new Date('2024-05-15'),
    startTime: '09:00',
    endTime: '12:00',
    status: 'scheduled',
    taskType: 'watering',
    description: 'Water newly planted trees in the south section',
    requiredSkills: ['Watering'],
    maxVolunteers: 5,
    assignedVolunteerIds: ['vol-3'],
    notes: 'Bring water containers',
    createdBy: 'vol-2',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  'assign-2': {
    id: 'assign-2',
    siteId: 'site-3',
    date: new Date('2024-05-18'),
    startTime: '10:00',
    endTime: '14:00',
    status: 'scheduled',
    taskType: 'planting',
    description: 'Plant new fruit trees in the community garden',
    requiredSkills: ['Planting'],
    maxVolunteers: 8,
    assignedVolunteerIds: ['vol-2', 'vol-4'],
    notes: 'Tools provided on site',
    createdBy: 'vol-1',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  'assign-3': {
    id: 'assign-3',
    siteId: 'site-2',
    date: new Date('2024-05-20'),
    startTime: '08:00',
    endTime: '11:00',
    status: 'scheduled',
    taskType: 'pruning',
    description: 'Prune overgrown branches in the park',
    requiredSkills: ['Pruning', 'Tree Identification'],
    maxVolunteers: 4,
    assignedVolunteerIds: [],
    notes: 'Experienced volunteers preferred',
    createdBy: 'vol-1',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
};

// Made with Bob
